name: Builds, tests & co

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2.2.9
        # dune-cache: true
        with:
          ocaml-compiler: "5.2"

      # Need to force opam to use CLI 2.1 because it defaults to 2.0
      - run: opam install . --cli=2.1 --depext-only

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      # Comment out until tests no longer require sudo permissions
      # - run: opam exec -- dune runtest
